[package]
name = "agntcy-slim-service"
edition = { workspace = true }
license = { workspace = true }
version = "0.13.3"
description = "Main service and public API to interact with SLIM data plane."

[lib]
name = "slim_service"
crate-type = ["lib"]

[features]
default = ["session"]
kubernetes = ["agntcy-slim-datapath/kubernetes"]
session = ["agntcy-slim-session", "agntcy-slim-persistence"]

[dependencies]
agntcy-slim-auth = { workspace = true }
agntcy-slim-config = { workspace = true }
agntcy-slim-datapath = { workspace = true }
agntcy-slim-persistence = { workspace = true, optional = true }
agntcy-slim-session = { workspace = true, optional = true }
agntcy-slim-version = { workspace = true }
display-error-chain = { workspace = true }
thiserror = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
twox-hash = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
agntcy-slim-controller = { workspace = true }
agntcy-slim-mls = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { package = "tokio_with_wasm", version = "0.10", features = ["sync", "macros", "rt", "time"] }
uuid = { workspace = true, features = ["v4", "js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
agntcy-slim-testing = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
tokio-test = { workspace = true }
tracing-test = { workspace = true, features = ["no-env-filter"] }
